kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "oneview-acm-bmhs" 
  namespace: open-cluster-management
spec:
  output:
    to:
      kind: DockerImage
      name: 'quay.io/feven/oneview-acm-bmhs:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.8'
  source:
    type: Git
    git:
      uri: 'https://github.com/feven-redhat/oneview-acm-bmhs'
  runPolicy: Serial
